### ISSUE TITLE
failed to get transaction from cache

### ISSUE THREAD

**Issue by bananasgroup** [corazawaf/coraza-spoa#59] opened 2023-04-13 03:12 UTC
Coraza-spoa got error after some day running, this is log message:
{"level":"error","ts":1681351374.8902335,"msg":"failed to get transaction from cache","transaction_id":"cc401a49-0815-4a3e-a355-69a6b4b08006","error":"Key not found.","app":"haproxy"}
What is the cause? How can I fix it?

**Comment by jptosso** [comment] 2023-04-13 03:35
Hey thank you for your report, this is a duplicate of #56. Please follow that ticket.

Regards,

**Closed by jptosso** 2023-04-13 03:35 UTC
